ARG python_image_v="python:3.10-buster"
FROM ${python_image_v}

ARG work_dir="/work/"
# コンテナにアクセスした際のデフォルトディレクトリ
WORKDIR ${work_dir}

# pip更新
RUN pip install --upgrade pip

# boto3インストール
RUN pip install boto3

# リージョン情報を設定する
ENV AWS_DEFAULT_REGION=us-east-1

# Bedrockに必要なモジュールをインストール
RUN pip install --no-build-isolation --force-reinstall \
    "boto3>=1.28.57" \
    "awscli>=1.29.57" \
    "botocore>=1.31.57" \
    "langchain==0.0.320"
